dotProcMan/Models/Enums/OutputType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotProcMan.Models.Enums
{
    public enum OutputType
    {
        Standard,
        Error,
        Input,
        Internal
    }
}

dotProcMan/Models/ErrorViewModel.cs
using System;

namespace dotProcMan.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

dotProcMan/Models/ListProcessItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotProcMan.Models
{
    public class ListProcessItem
    {
        public Guid ID { get; set; }

        public string Name { get; set; }

        public bool IsRunning { get; set; }
    }
}

dotProcMan/Models/ListProcessesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotProcMan.Models
{
    public class ListProcessesViewModel
    {
        public IEnumerable<ListProcessItem> Processes { get; set; }
    }
}

dotProcMan/Models/ManagedProcess.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotProcMan.Models
{
    public class ManagedProcess
    {
        public Guid ID { get; }

        public string Name { get; set; }

        public string FileName { get; set; }

        public string Args { get; set; }

        public string WorkingDirectory { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public int StartDelay { get; set; }

        public bool AutoRestart { get; set; }

        public string RestartSchedule { get; set; }

        public ManagedProcess()
        {
            this.ID = Guid.NewGuid();
        }

        #region Overrides
        /// <summary>
        /// Determines whether the specified <see cref="System.Object" />, is equal to this instance.
        /// </summary>
        /// <param name="obj">The <see cref="System.Object" /> to compare with this instance.</param>
        /// <returns>
        ///   <c>true</c> if the specified <see cref="System.Object" /> is equal to this instance; otherwise, <c>false</c>.
        /// </returns>
        public override bool Equals(object obj)
        {
            var process = obj as ManagedProcess;
            return process != null &&
                   ID.Equals(process.ID);
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        /// <returns>
        /// A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. 
        /// </returns>
        public override int GetHashCode()
        {
            return HashCode.Combine(ID);
        }

        /// <summary>
        /// Returns a <see cref="System.String" /> that represents this instance.
        /// </summary>
        /// <returns>
        /// A <see cref="System.String" /> that represents this instance.
        /// </returns>
        public override string ToString()
        {
            return $"{Name} ({FileName})";
        }
        #endregion
    }
}

dotProcMan/Models/ProcessOutputRow.cs
using dotProcMan.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotProcMan.Models
{
    public class ProcessOutputRow
    {
        public DateTime Timestamp { get; set; }

        public string Data { get; set; }

        public OutputType Type { get; set; }
    }
}

dotProcMan/Models/ShowOutputViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotProcMan.Models
{
    public class ShowOutputViewModel
    {
        public Guid ProcessID { get; set; }

        public string ProcessName { get; set; }

        public IEnumerable<ProcessOutputRow> Rows { get; set; }
    }
}

dotProcMan/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using dotProcMan.Models;
using dotProcMan.Services;

namespace dotProcMan.Controllers
{
    public class HomeController : Controller
    {
        private IProcessManagerService processManagerService;

        public HomeController(IProcessManagerService processManagerService)
        {
            this.processManagerService = processManagerService;
        }

        public IActionResult Index()
        {
            ListProcessesViewModel model = new ListProcessesViewModel();
            model.Processes = processManagerService.GetProcesses().Select(p => new ListProcessItem
            {
                ID = p.ID,
                Name = p.Name,
                IsRunning = processManagerService.IsRunning(p.ID)
            });

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

dotProcMan/Controllers/ProcessAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dotProcMan.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace dotProcMan.Controllers
{
    [Route("api/process")]
    [ApiController]
    public class ProcessAPIController : ControllerBase
    {
        private IProcessManagerService processManagerService;

        public ProcessAPIController(IProcessManagerService processManagerService)
        {
            this.processManagerService = processManagerService;
        }

        [HttpPost]
        [Route("start")]
        public IActionResult Start(Guid id)
        {
            bool result = processManagerService.Start(id);
            return Ok(result);
        }

        [HttpPost]
        [Route("stop")]
        public IActionResult Stop(Guid id)
        {
            bool result = processManagerService.Stop(id);
            return Ok(result);
        }

        [HttpPost]
        [Route("restart")]
        public IActionResult Restart(Guid id)
        {
            bool result = processManagerService.Restart(id);
            return Ok(result);
        }
    }
}

dotProcMan/Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dotProcMan.Models;
using dotProcMan.Services;
using Microsoft.AspNetCore.Mvc;

namespace dotProcMan.Controllers
{
    public class ProcessController : Controller
    {
        private IProcessOutputService processOutputService;
        private IProcessManagerService processManagerService;

        public ProcessController(IProcessManagerService processManagerService, IProcessOutputService processOutputService)
        {
            this.processOutputService = processOutputService;
            this.processManagerService = processManagerService;
        }

        public IActionResult Output(Guid id)
        {
            ShowOutputViewModel model = new ShowOutputViewModel();
            model.ProcessID = id;
            model.ProcessName = processManagerService.GetName(id);
            model.Rows = processOutputService.Get(id, 100);

            if (model.ProcessName == null)
                return NotFound();

            return View(model);
        }

        public IActionResult Details(Guid id)
        {
            ManagedProcess process = processManagerService.GetProcess(id);

            if (process == null)
                return NotFound();

            return View(process);
        }

        [HttpPost]
        public IActionResult SendInput(Guid id, string data)
        {
            processManagerService.SendInput(id, data);
            return RedirectToAction("Output", new { id = id });
        }
    }
}

dotProcMan/Views/Home/Index.cshtml
@model dotProcMan.Models.ListProcessesViewModel
@{
    ViewData["Title"] = "Processes";
}

<h1 class="mb-3">Processes</h1>

<table class="table table-sm">
    <thead>
        <tr>
            <th>Name</th>
            <th>Running</th>
            <th style="width: 120px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var process in Model.Processes)
        {
            <tr>
                <td><a asp-controller="Process" asp-action="Output" asp-route-id="@process.ID">@process.Name</a></td>
                <td>@(process.IsRunning ? "Yes" : "No")</td>
                <td class="text-center">
                    <div class="dropdown">
                        <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdown-@process.ID" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Actions
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-controller="Process" asp-action="Details" asp-route-id="@process.ID">Details</a>
                            <a class="dropdown-item" href="#" data-jsclick="start" data-process-id="@process.ID">Start</a>
                            <a class="dropdown-item" href="#" data-jsclick="stop" data-process-id="@process.ID">Stop</a>
                            <a class="dropdown-item" href="#" data-jsclick="restart" data-process-id="@process.ID">Restart</a>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

dotProcMan/Views/Process/Details.cshtml
@model dotProcMan.Models.ManagedProcess

@{
    ViewData["Title"] = "Details";
}

<h1>@Model.Name - Details</h1>

<hr/>

<dl class="row">
    <dt class="col-2">Name</dt>
    <dd class="col-10">@Model.Name&nbsp;</dd>

    <dt class="col-2">File name</dt>
    <dd class="col-10">@Model.FileName&nbsp;</dd>

    <dt class="col-2">Arguments</dt>
    <dd class="col-10">@Model.Args&nbsp;</dd>

    <dt class="col-2">Working directory</dt>
    <dd class="col-10">@Model.WorkingDirectory&nbsp;</dd>

    <dt class="col-2">Username</dt>
    <dd class="col-10">@Model.Username&nbsp;</dd>

    <dt class="col-2">Password</dt>
    <dd class="col-10">@(!string.IsNullOrWhiteSpace(Model.Password) ? "*****" : string.Empty)&nbsp;</dd>

    <dt class="col-2">Start delay</dt>
    <dd class="col-10">@Model.StartDelay&nbsp;</dd>

    <dt class="col-2">Auto restart</dt>
    <dd class="col-10">@(Model.AutoRestart ? "Yes" : "No")&nbsp;</dd>
</dl>

dotProcMan/Views/Process/Output.cshtml
@model dotProcMan.Models.ShowOutputViewModel

@{
    ViewData["Title"] = "Output";
}

<h1 class="mb-3">@Model.ProcessName - Output</h1>

<pre class="output-box pre-scrollable">
    @foreach(var row in Model.Rows)
    {
<span class="output-type-@row.Type.ToString().ToLower()"><span class="font-weight-bold">@row.Timestamp:</span> @row.Data</span> @Environment.NewLine
    }
</pre>

<form method="post" asp-action="SendInput">
    <input type="hidden" name="id" value="@Model.ProcessID" />
    <div class="input-group mb-3">
        <input type="text" name="data" class="form-control" placeholder="Input command" aria-label="Input command" aria-describedby="button-addon2">
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit" id="button-addon2">Send</button>
        </div>
    </div>
</form>

dotProcMan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotProcMan</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/npm/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/libs.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark mb-3">
        <div class="container">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">dotProcMan</a>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <hr />
    <div class="container">
        <footer>
            <p>&copy; @DateTime.Today.Year - dotProcMan</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/npm/jquery/dist/jquery.js"></script>
        <script src="~/npm/popper.js/dist/umd/popper.js"></script>
        <script src="~/npm/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/main.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/libs.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>